export enum SERVICE_IDENTIFIER {
  BATTLE_SERVICE = 'BATTLE_SERVICE',
  CARTRIDGES_SERVICE = 'CARTRIDGES_SERVICE',
  DEFENDERS_SERVICE = 'DEFENDERS_SERVICE',
  ENEMIES_SERVICE = 'ENEMIES_SERVICE',
  BONUS_SERVICE = 'BONUS_SERVICE',
}
